services:   
    odiseo_messaging.form.handler.message:
        class: Odiseo\Bundle\MessagingBundle\Form\Handler\MessageFormHandler
        arguments:  [ "@service_container"]
    
    odiseo_messaging.form.type.message:
        class: Odiseo\Bundle\MessagingBundle\Form\Type\MessageFormType
        arguments:  [ "%odiseo_messaging.model.message.class%" ]
        tags:
            - { name: form.type, alias: odiseo_messaging_message }