services:
    odiseo_messaging.service.thread_message:
        class: Odiseo\Bundle\MessagingBundle\Services\ThreadMessageService
        arguments:  ["@doctrine.orm.entity_manager", "%odiseo_messaging.model.thread.class%", "%odiseo_messaging.model.thread_metadata.class%", "@fos_message.message_manager"]