odiseo_messaging_list:
    path:     /{threadId}
    defaults: { _controller: "odiseo_messaging.controller.messaging:listAction" }
    requirements:
        threadId:  \d+

odiseo_messaging_list_creator_topic:
    path:     /{creatorId}/{topicId}
    defaults: { _controller: "odiseo_messaging.controller.messaging:listWithCreatorAndTopicAction" }
    requirements:
        creatorId:  \d+
        thretopicId:  \d+

odiseo_messaging_send:
    path:     /send/{threadId}
    defaults: { _controller: "odiseo_messaging.controller.messaging:sendMessageAction" }
    requirements:
        threadId:  \d+

odiseo_messaging_update_list:
    path:     /updateList/{messageId}
    defaults: { _controller: "odiseo_messaging.controller.messaging:updateMessageListAction" }
    requirements:
        messageId:  \d+